import { useEffect, useState } from "react";
import { AudiotrackRounded, CameraAltRounded, CheckCircleRounded, ContentCutRounded, DescriptionRounded, MedicationRounded, PictureAsPdfRounded, UploadRounded, VaccinesRounded } from "@mui/icons-material";
import { Alert, Box, Button, CircularProgress, Dialog, DialogActions, DialogContent, FormControl, InputLabel, MenuItem, Select, Stack, TextField, Typography } from "@mui/material";
import type { Pet } from "./types";
import { hasSupabase, supabase } from "./lib/supabase";

type RecordData={recordType:string;title:string;date:string;dateGregorian:string;clinic:string;veterinarian:string;diagnosis:string;medications:string;notes:string;confidence?:number};
const empty:RecordData={recordType:"سایر",title:"",date:"",dateGregorian:"",clinic:"",veterinarian:"",diagnosis:"",medications:"",notes:""};
const recordTypes=["نسخه","تشخیص","آزمایش","تصویربرداری","واکسن","سایر"];
type DirectMode="RABIES_VACCINATION"|"ANTI_PARASITIC_TREATMENT"|"OTHER_VACCINATION"|"SURGERY";
type CareDraft={type:Exclude<DirectMode,"SURGERY">;substance_name:string;administered_at:string;administered_at_jalali:string;next_relevant_date:string;next_relevant_date_jalali:string;veterinarian_name:string;notes:string};
type SurgeryDraft={procedure_name:string;performed_at:string;performed_at_jalali:string;veterinarian_name:string;description:string};
const directOptions:{mode:DirectMode|"SMART";title:string;description:string;icon:React.ReactNode}[]=[
  {mode:"RABIES_VACCINATION",title:"ثبت واکسن هاری",description:"نام واکسن، تاریخ تزریق و اعتبار بعدی",icon:<VaccinesRounded/>},
  {mode:"ANTI_PARASITIC_TREATMENT",title:"ضد انگل",description:"دارو/محلول، تاریخ مصرف و نوبت بعدی",icon:<MedicationRounded/>},
  {mode:"SURGERY",title:"جراحی",description:"نام پروسیجر، تاریخ، دامپزشک و توضیحات",icon:<ContentCutRounded/>},
  {mode:"OTHER_VACCINATION",title:"سایر واکسن‌ها",description:"واکسن‌های غیر از هاری",icon:<VaccinesRounded/>},
  {mode:"SMART",title:"بارگذاری مدرک",description:"عکس مدرک را اضافه کنید تا بعداً هوشمند خوانده شود",icon:<UploadRounded/>},
];
const careLabels:Record<CareDraft["type"],{title:string;substance:string;date:string;next:string;button:string}>={
  RABIES_VACCINATION:{title:"واکسن هاری",substance:"واکسن استفاده‌شده",date:"تاریخ واکسیناسیون",next:"اعتبار تا",button:"ثبت واکسن هاری"},
  ANTI_PARASITIC_TREATMENT:{title:"ضد انگل",substance:"نام دارو / محصول",date:"تاریخ مصرف",next:"نوبت بعدی",button:"ثبت ضد انگل"},
  OTHER_VACCINATION:{title:"سایر واکسن‌ها",substance:"واکسن استفاده‌شده",date:"تاریخ واکسیناسیون",next:"اعتبار تا",button:"ثبت واکسن"},
};
const emptyCareDraft=(type:CareDraft["type"]):CareDraft=>({type,substance_name:"",administered_at:"",administered_at_jalali:"",next_relevant_date:"",next_relevant_date_jalali:"",veterinarian_name:"",notes:""});
const emptySurgeryDraft: SurgeryDraft={procedure_name:"",performed_at:"",performed_at_jalali:"",veterinarian_name:"",description:""};
const persianMonths = ["فروردین","اردیبهشت","خرداد","تیر","مرداد","شهریور","مهر","آبان","آذر","دی","بهمن","اسفند"];
const toEnglishDigits = (value:string) => value.replace(/[۰-۹]/g, digit => String("۰۱۲۳۴۵۶۷۸۹".indexOf(digit))).replace(/[٠-٩]/g, digit => String("٠١٢٣٤٥٦٧٨٩".indexOf(digit)));
const numericOnly = (value:string) => toEnglishDigits(value).replace(/\D/g,"");
const pad2 = (value:number) => String(value).padStart(2,"0");
function jalaliToGregorian(jy:number,jm:number,jd:number) {jy+=1595;let days=-355668+(365*jy)+Math.floor(jy/33)*8+Math.floor(((jy%33)+3)/4)+jd+(jm<7?(jm-1)*31:((jm-7)*30)+186);let gy=400*Math.floor(days/146097);days%=146097;if(days>36524){gy+=100*Math.floor(--days/36524);days%=36524;if(days>=365)days++;}gy+=4*Math.floor(days/1461);days%=1461;if(days>365){gy+=Math.floor((days-1)/365);days=(days-1)%365;}let gd=days+1;const sal=[0,31,((gy%4===0&&gy%100!==0)||gy%400===0)?29:28,31,30,31,30,31,31,30,31,30,31];let gm=0;for(gm=1;gm<=12&&gd>sal[gm];gm++)gd-=sal[gm];return [gy,gm,gd] as const;}
function gregorianToJalali(gy:number,gm:number,gd:number) {const gdm=[0,31,59,90,120,151,181,212,243,273,304,334];let jy=(gy<=1600)?0:979;gy-=(gy<=1600)?621:1600;let gy2=(gm>2)?gy+1:gy;let days=(365*gy)+Math.floor((gy2+3)/4)-Math.floor((gy2+99)/100)+Math.floor((gy2+399)/400)-80+gd+gdm[gm-1];jy+=33*Math.floor(days/12053);days%=12053;jy+=4*Math.floor(days/1461);days%=1461;if(days>365){jy+=Math.floor((days-1)/365);days=(days-1)%365;}const jm=days<186?1+Math.floor(days/31):7+Math.floor((days-186)/30);const jd=1+(days<186?days%31:(days-186)%30);return [jy,jm,jd] as const;}
const jalaliToIso=(jy:string,jm:string,jd:string)=>{const year=Number(jy),month=Number(jm||"1"),day=Number(jd||"1");if(!year)return "";const[gy,gm,gd]=jalaliToGregorian(year,month,day);return `${gy}-${pad2(gm)}-${pad2(gd)}`;};
const jalaliPartsToValue=(year:string,month:string,day:string)=>year?`${year}-${pad2(Number(month||"1"))}-${pad2(Number(day||"1"))}`:"";
const jalaliValueToParts=(value?:string|null)=>{const[year="",month="",day=""]=(value||"").split("-");return{year,month:month?String(Number(month)):"",day:day?String(Number(day)):""};};
const jalaliMonthDays=(year:string,month:string)=>{const m=Number(month||"1"),y=Number(year);if(m<=6)return 31;if(m<=11)return 30;if(!y)return 29;const[startGy,startGm,startGd]=jalaliToGregorian(y,12,1);const[endGy,endGm,endGd]=jalaliToGregorian(y+1,1,1);return Math.round((Date.UTC(endGy,endGm-1,endGd)-Date.UTC(startGy,startGm-1,startGd))/86400000);};
const thisJalaliYear=gregorianToJalali(new Date().getFullYear(),new Date().getMonth()+1,new Date().getDate())[0];
const jalaliYears=Array.from({length:35},(_,i)=>thisJalaliYear-i);
function JalaliDateField({label,value,onChange}:{label:string;value?:string;onChange:(next:{jalali:string;gregorian:string})=>void}){const parts=jalaliValueToParts(value);const update=(key:"year"|"month"|"day",raw:string)=>{const clean=numericOnly(raw).slice(0,key==="year"?4:2);const next={...parts,[key]:clean};if(key==="month"||key==="year"){const maxDay=jalaliMonthDays(key==="year"?clean:next.year,key==="month"?clean:next.month);if(Number(next.day)>maxDay)next.day="";}const jalali=jalaliPartsToValue(next.year,next.month,next.day);onChange({jalali,gregorian:jalali?jalaliToIso(next.year,next.month,next.day):""});};return <Box className="pet-birth-card subtle"><Typography variant="subtitle2">{label}</Typography><div className="form-row birth-row"><FormControl><InputLabel>سال</InputLabel><Select label="سال" value={parts.year} onChange={e=>update("year",String(e.target.value))}><MenuItem value="">ثبت نشده</MenuItem>{jalaliYears.map(y=><MenuItem key={y} value={String(y)}>{y}</MenuItem>)}</Select></FormControl><FormControl><InputLabel>ماه</InputLabel><Select label="ماه" value={parts.month} onChange={e=>update("month",String(e.target.value))}><MenuItem value="">فروردین پیش‌فرض</MenuItem>{persianMonths.map((m,i)=><MenuItem key={m} value={String(i+1)}>{m}</MenuItem>)}</Select></FormControl><FormControl><InputLabel>روز</InputLabel><Select label="روز" value={parts.day} onChange={e=>update("day",String(e.target.value))}><MenuItem value="">روز ۱ پیش‌فرض</MenuItem>{Array.from({length:jalaliMonthDays(parts.year,parts.month)},(_,i)=>i+1).map(day=><MenuItem key={day} value={String(day)}>{day}</MenuItem>)}</Select></FormControl></div>{value&&<Typography color="text.secondary" variant="caption">ذخیره شمسی: {value}</Typography>}</Box>;}
const fileToDataUrl=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);});
async function extractDocument(file:File){const{data,error}=await supabase.functions.invoke("extract-medical-document",{body:{image:await fileToDataUrl(file),recordType:"تشخیص خودکار نوع مدرک"}});if(error||data?.error)throw new Error(data?.error||error?.message||"خواندن تصویر انجام نشد");return data as RecordData;}

export default function SmartEntryModal({open,onClose,onSaved,pets}:{open:boolean;onClose:()=>void;onSaved:()=>void;pets:Pet[]}) {
  const[step,setStep]=useState<"pet"|"type"|"direct"|"source"|"analyzing"|"review">("pet"),[petId,setPetId]=useState(""),[directMode,setDirectMode]=useState<DirectMode|null>(null),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[values,setValues]=useState<RecordData>(empty);
  const[careDraft,setCareDraft]=useState<CareDraft>(emptyCareDraft("RABIES_VACCINATION")),[surgeryDraft,setSurgeryDraft]=useState<SurgeryDraft>(emptySurgeryDraft);
  useEffect(()=>{if(open){setStep("pet");setPetId("");setDirectMode(null);setFile(null);setPreview("");setBusy(false);setError("");setValues(empty);setCareDraft(emptyCareDraft("RABIES_VACCINATION"));setSurgeryDraft(emptySurgeryDraft);}},[open]);
  const set=(key:keyof RecordData)=>(e:{target:{value:unknown}})=>setValues(v=>({...v,[key]:String(e.target.value)}));
  const chooseDirect=(mode:DirectMode)=>{setDirectMode(mode);setError("");if(mode==="SURGERY")setSurgeryDraft(emptySurgeryDraft);else setCareDraft(emptyCareDraft(mode));setStep("direct");};
  const saveDirect=async(e:React.FormEvent)=>{
    e.preventDefault();if(!hasSupabase||!petId||!directMode)return setError("اتصال دیتابیس یا پرونده پت در دسترس نیست.");
    setBusy(true);setError("");
    if(directMode==="SURGERY"){
      const payload={pet_id:petId,procedure_name:surgeryDraft.procedure_name||null,description:surgeryDraft.description||null,performed_at:surgeryDraft.performed_at||null,performed_at_jalali:surgeryDraft.performed_at_jalali||null,veterinarian_name:surgeryDraft.veterinarian_name||null,updated_at:new Date().toISOString()};
      const{error:dbError}=await supabase.from("pet_surgical_history").insert(payload);
      setBusy(false);if(dbError)return setError("ذخیره جراحی انجام نشد.");onClose();onSaved();return;
    }
    const payload={pet_id:petId,type:careDraft.type,substance_name:careDraft.substance_name||null,administered_at:careDraft.administered_at||null,administered_at_jalali:careDraft.administered_at_jalali||null,next_relevant_date:careDraft.next_relevant_date||null,next_relevant_date_jalali:careDraft.next_relevant_date_jalali||null,veterinarian_name:careDraft.veterinarian_name||null,notes:careDraft.notes||null,updated_at:new Date().toISOString()};
    const{error:dbError}=await supabase.from("pet_preventive_care_records").insert(payload);
    setBusy(false);if(dbError)return setError("ذخیره مراقبت پیشگیرانه انجام نشد.");onClose();onSaved();
  };
  const analyze=async(selected:File)=>{
    setError("");if(!selected.type.startsWith("image/"))return setError("در این مرحله فقط تصویر قابل ثبت است.");if(selected.size>10*1024*1024)return setError("حجم تصویر باید کمتر از ۱۰ مگابایت باشد.");
    setFile(selected);setPreview(await fileToDataUrl(selected));setStep("analyzing");setBusy(true);
    try{setValues(await extractDocument(selected));setStep("review");}catch(e){setError(e instanceof Error?e.message:"خواندن تصویر انجام نشد");setStep("source");}finally{setBusy(false);}
  };
  const save=async(e:React.FormEvent)=>{
    e.preventDefault();if(!hasSupabase||!file)return setError("اتصال دیتابیس یا تصویر در دسترس نیست.");if(!values.title)return setError("عنوان را وارد کنید.");
    setBusy(true);setError("");const safeName=file.name.replace(/[^a-zA-Z0-9._-]/g,"-"),attachmentPath=`${petId}/${crypto.randomUUID()}-${safeName}`;const upload=await supabase.storage.from("pet-documents").upload(attachmentPath,file,{upsert:false});if(upload.error){setBusy(false);return setError("بارگذاری تصویر انجام نشد.");}
    const{data:userData}=await supabase.auth.getUser();const{error:dbError}=await supabase.from("medical_records").insert({pet_id:petId,record_type:values.recordType,title:values.title||null,event_date:values.dateGregorian||null,event_date_jalali:values.date||null,event_date_gregorian:values.dateGregorian||null,clinic:values.clinic||null,veterinarian:values.veterinarian||null,diagnosis:values.diagnosis||null,medications:values.medications||null,notes:values.notes||null,attachment_path:attachmentPath,created_by:userData.user?.id});setBusy(false);if(dbError)return setError("ذخیره اطلاعات انجام نشد.");onClose();onSaved();
  };
  const selectedPet=pets.find(p=>p.id===petId),progress=step==="pet"?1:(step==="type"||step==="source")?2:3;
  const fileInput=(capture?:boolean)=><Box component="label" sx={{display:"block"}}><input hidden type="file" accept="image/*" capture={capture?"environment":undefined} onChange={e=>{const f=e.target.files?.[0];if(f)void analyze(f);}}/><button type="button" className={`source-option ${capture?"primary":""}`}>{capture?<CameraAltRounded/>:<UploadRounded/>}<b>{capture?"گرفتن عکس":"انتخاب عکس"}</b><small>{capture?"با دوربین موبایل":"از گالری یا فایل‌ها"}</small></button></Box>;
  const directTitle=directMode==="SURGERY"?"جراحی":directMode?careLabels[directMode].title:"ثبت رویداد";
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="md" className="quick-entry-modal" fullScreen={false}><header className="quick-entry-head"><span>{progress} از ۳</span><Typography variant="h5" component="h2">{step==="pet"?"برای کدام پرونده؟":step==="type"?"چه چیزی می‌خواهید ثبت کنید؟":step==="direct"?directTitle:step==="source"?"چطور می‌خواهید مدرک را اضافه کنید؟":step==="analyzing"?"در حال خواندن مدرک":"بررسی و ثبت اطلاعات"}</Typography><Typography color="text.secondary">{step==="pet"?"پرونده پتی را که این رویداد به آن مربوط است انتخاب کنید.":step==="type"?`${selectedPet?.name||"پت"} انتخاب شده؛ اگر نوع رویداد را می‌دانید مستقیم ثبت کنید.`:step==="direct"?"همان اطلاعات فرم مراقبت پیشگیرانه یا جراحی را وارد کنید.":step==="source"?`${selectedPet?.name||"پت"} انتخاب شده؛ مدرک را برای مسیر هوشمند بارگذاری کنید.`:step==="analyzing"?"هوش مصنوعی اطلاعات پزشکی را از تصویر استخراج می‌کند.":"اطلاعات استخراج‌شده را بررسی و اصلاح کنید."}</Typography><div className="quick-progress">{[1,2,3].map(x=><i key={x} className={progress>=x?"done":""}/>)}</div></header>{error&&<Alert severity="error" sx={{mx:3,mt:2}}>{error}</Alert>}
  {step==="pet"&&<div className="pet-choice-list">{pets.map(p=><button key={p.id} onClick={()=>{setPetId(p.id);setStep("type");}}><span>{p.name.slice(0,1)}</span><div><b>{p.name}</b><small>{[p.species,p.breed].filter(Boolean).join(" · ")}</small></div><i>←</i></button>)}</div>}
  {step==="type"&&<div className="source-step"><div className="source-grid">{directOptions.map(option=><button key={option.mode} type="button" className={`source-option ${option.mode==="SMART"?"primary":""}`} onClick={()=>option.mode==="SMART"?setStep("source"):chooseDirect(option.mode)}>{option.icon}<b>{option.title}</b><small>{option.description}</small></button>)}</div><Button onClick={()=>setStep("pet")}>تغییر پرونده</Button></div>}
  {step==="direct"&&directMode&&<Box component="form" onSubmit={saveDirect}><DialogContent className="quick-review"><Stack spacing={2} className="extracted-form">{directMode==="SURGERY"?<><TextField label="جراحی / پروسیجر" value={surgeryDraft.procedure_name} onChange={e=>setSurgeryDraft(v=>({...v,procedure_name:e.target.value}))}/><JalaliDateField label="تاریخ جراحی شمسی" value={surgeryDraft.performed_at_jalali} onChange={next=>setSurgeryDraft(v=>({...v,performed_at_jalali:next.jalali,performed_at:next.gregorian}))}/><TextField label="نام دامپزشک" value={surgeryDraft.veterinarian_name} onChange={e=>setSurgeryDraft(v=>({...v,veterinarian_name:e.target.value}))}/><TextField label="توضیحات" value={surgeryDraft.description} onChange={e=>setSurgeryDraft(v=>({...v,description:e.target.value}))} multiline minRows={2}/></>:<><TextField label={careLabels[careDraft.type].substance} value={careDraft.substance_name} onChange={e=>setCareDraft(v=>({...v,substance_name:e.target.value}))}/><JalaliDateField label={`${careLabels[careDraft.type].date} شمسی`} value={careDraft.administered_at_jalali} onChange={next=>setCareDraft(v=>({...v,administered_at_jalali:next.jalali,administered_at:next.gregorian}))}/><JalaliDateField label={`${careLabels[careDraft.type].next} شمسی`} value={careDraft.next_relevant_date_jalali} onChange={next=>setCareDraft(v=>({...v,next_relevant_date_jalali:next.jalali,next_relevant_date:next.gregorian}))}/><TextField label="نام دامپزشک" value={careDraft.veterinarian_name} onChange={e=>setCareDraft(v=>({...v,veterinarian_name:e.target.value}))}/><TextField label="یادداشت" value={careDraft.notes} onChange={e=>setCareDraft(v=>({...v,notes:e.target.value}))} multiline minRows={2}/></>}</Stack></DialogContent><DialogActions><Button onClick={()=>setStep("type")}>بازگشت</Button><Button variant="contained" type="submit" disabled={busy}>{busy?<CircularProgress size={20}/>:directMode==="SURGERY"?"ثبت جراحی":careLabels[careDraft.type].button}</Button></DialogActions></Box>}
  {step==="source"&&<div className="source-step"><div className="source-grid">{fileInput(true)}{fileInput()}<button className="source-option disabled" disabled><PictureAsPdfRounded/><b>فایل PDF</b><small>به‌زودی</small></button><button className="source-option disabled" disabled><AudiotrackRounded/><b>ضبط صدا</b><small>به‌زودی</small></button><button className="source-option disabled" disabled><AudiotrackRounded/><b>آپلود صوت</b><small>به‌زودی</small></button></div><Button onClick={()=>setStep("type")}>بازگشت به انتخاب نوع</Button></div>}
  {step==="analyzing"&&<div className="ai-reading"><div className="ai-preview">{preview&&<img src={preview} alt="مدرک پزشکی"/>}</div><CircularProgress/><b>در حال استخراج اطلاعات…</b><small>نسخه، تشخیص، داروها و تاریخ شناسایی می‌شوند.</small></div>}
  {step==="review"&&<Box component="form" onSubmit={save}><DialogContent className="review-grid quick-review"><aside className="document-preview">{preview?<img src={preview} alt="تصویر مدرک پزشکی"/>:<DescriptionRounded/>}<b>تصویر اصلی</b><span>همراه رکورد ذخیره می‌شود</span></aside><Stack spacing={2} className="extracted-form"><Alert severity="success" icon={<CheckCircleRounded/>}>اطلاعات از تصویر استخراج شد؛ قبل از ثبت نهایی بازبینی کنید.</Alert><FormControl size="small"><InputLabel>نوع مدرک</InputLabel><Select label="نوع مدرک" value={values.recordType} onChange={set("recordType")}>{recordTypes.map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</Select></FormControl><TextField label="عنوان" required value={values.title} onChange={set("title")}/><JalaliDateField label="تاریخ شمسی" value={values.date} onChange={next=>setValues(v=>({...v,date:next.jalali,dateGregorian:next.gregorian}))}/><div className="form-row"><TextField label="کلینیک" value={values.clinic} onChange={set("clinic")}/><TextField label="دامپزشک" value={values.veterinarian} onChange={set("veterinarian")}/></div><TextField multiline rows={2} label="تشخیص" value={values.diagnosis} onChange={set("diagnosis")}/><TextField multiline rows={2} label="داروها و دستور مصرف" value={values.medications} onChange={set("medications")}/><TextField multiline rows={2} label="یادداشت" value={values.notes} onChange={set("notes")}/></Stack></DialogContent><DialogActions><Button onClick={()=>setStep("source")}>تغییر تصویر</Button><Button variant="contained" type="submit" disabled={busy}>{busy?<CircularProgress size={20}/>:`ثبت در پرونده ${selectedPet?.name}`}</Button></DialogActions></Box>}
  </Dialog>;
}
