import { useEffect, useState } from "react";
import { AudiotrackRounded, CameraAltRounded, CheckCircleRounded, DescriptionRounded, PictureAsPdfRounded, UploadRounded } from "@mui/icons-material";
import { Alert, Box, Button, CircularProgress, Dialog, DialogActions, DialogContent, FormControl, InputLabel, MenuItem, Select, Stack, TextField, Typography } from "@mui/material";
import type { Pet } from "./types";
import { hasSupabase, supabase } from "./lib/supabase";

type RecordData={recordType:string;title:string;date:string;clinic:string;veterinarian:string;diagnosis:string;medications:string;notes:string;confidence?:number};
const empty:RecordData={recordType:"سایر",title:"",date:"",clinic:"",veterinarian:"",diagnosis:"",medications:"",notes:""};
const recordTypes=["نسخه","تشخیص","آزمایش","تصویربرداری","واکسن","سایر"];
const fileToDataUrl=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);});
async function extractDocument(file:File){const{data,error}=await supabase.functions.invoke("extract-medical-document",{body:{image:await fileToDataUrl(file),recordType:"تشخیص خودکار نوع مدرک"}});if(error||data?.error)throw new Error(data?.error||error?.message||"خواندن تصویر انجام نشد");return data as RecordData;}

export default function SmartEntryModal({open,onClose,onSaved,pets}:{open:boolean;onClose:()=>void;onSaved:()=>void;pets:Pet[]}) {
  const[step,setStep]=useState<"pet"|"source"|"analyzing"|"review">("pet"),[petId,setPetId]=useState(""),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[values,setValues]=useState<RecordData>(empty);
  useEffect(()=>{if(open){setStep("pet");setPetId("");setFile(null);setPreview("");setBusy(false);setError("");setValues(empty);}},[open]);
  const set=(key:keyof RecordData)=>(e:{target:{value:unknown}})=>setValues(v=>({...v,[key]:String(e.target.value)}));
  const analyze=async(selected:File)=>{
    setError("");if(!selected.type.startsWith("image/"))return setError("در این مرحله فقط تصویر قابل ثبت است.");if(selected.size>10*1024*1024)return setError("حجم تصویر باید کمتر از ۱۰ مگابایت باشد.");
    setFile(selected);setPreview(await fileToDataUrl(selected));setStep("analyzing");setBusy(true);
    try{setValues(await extractDocument(selected));setStep("review");}catch(e){setError(e instanceof Error?e.message:"خواندن تصویر انجام نشد");setStep("source");}finally{setBusy(false);}
  };
  const save=async(e:React.FormEvent)=>{
    e.preventDefault();if(!hasSupabase||!file)return setError("اتصال دیتابیس یا تصویر در دسترس نیست.");if(!values.title)return setError("عنوان را وارد کنید.");
    setBusy(true);setError("");const safeName=file.name.replace(/[^a-zA-Z0-9._-]/g,"-"),attachmentPath=`${petId}/${crypto.randomUUID()}-${safeName}`;const upload=await supabase.storage.from("pet-documents").upload(attachmentPath,file,{upsert:false});if(upload.error){setBusy(false);return setError("بارگذاری تصویر انجام نشد.");}
    const{data:userData}=await supabase.auth.getUser();const{error:dbError}=await supabase.from("medical_records").insert({pet_id:petId,record_type:values.recordType,title:values.title||null,event_date:values.date||null,clinic:values.clinic||null,veterinarian:values.veterinarian||null,diagnosis:values.diagnosis||null,medications:values.medications||null,notes:values.notes||null,attachment_path:attachmentPath,created_by:userData.user?.id});setBusy(false);if(dbError)return setError("ذخیره اطلاعات انجام نشد.");onClose();onSaved();
  };
  const selectedPet=pets.find(p=>p.id===petId),progress=step==="pet"?1:step==="source"?2:3;
  const fileInput=(capture?:boolean)=><Box component="label" sx={{display:"block"}}><input hidden type="file" accept="image/*" capture={capture?"environment":undefined} onChange={e=>{const f=e.target.files?.[0];if(f)void analyze(f);}}/><button type="button" className={`source-option ${capture?"primary":""}`}>{capture?<CameraAltRounded/>:<UploadRounded/>}<b>{capture?"گرفتن عکس":"انتخاب عکس"}</b><small>{capture?"با دوربین موبایل":"از گالری یا فایل‌ها"}</small></button></Box>;
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="md" className="quick-entry-modal" fullScreen={false}><header className="quick-entry-head"><span>{progress} از ۳</span><Typography variant="h5" component="h2">{step==="pet"?"برای کدام پرونده؟":step==="source"?"چطور می‌خواهید اضافه کنید؟":step==="analyzing"?"در حال خواندن مدرک":"بررسی و ثبت اطلاعات"}</Typography><Typography color="text.secondary">{step==="pet"?"پرونده پتی را که این مدرک به آن مربوط است انتخاب کنید.":step==="source"?`${selectedPet?.name||"پت"} انتخاب شده؛ نوع ورودی را مشخص کنید.`:step==="analyzing"?"هوش مصنوعی اطلاعات پزشکی را از تصویر استخراج می‌کند.":"اطلاعات استخراج‌شده را بررسی و اصلاح کنید."}</Typography><div className="quick-progress">{[1,2,3].map(x=><i key={x} className={progress>=x?"done":""}/>)}</div></header>{error&&<Alert severity="error" sx={{mx:3,mt:2}}>{error}</Alert>}
  {step==="pet"&&<div className="pet-choice-list">{pets.map(p=><button key={p.id} onClick={()=>{setPetId(p.id);setStep("source");}}><span>{p.name.slice(0,1)}</span><div><b>{p.name}</b><small>{[p.species,p.breed].filter(Boolean).join(" · ")}</small></div><i>←</i></button>)}</div>}
  {step==="source"&&<div className="source-step"><div className="source-grid">{fileInput(true)}{fileInput()}<button className="source-option disabled" disabled><PictureAsPdfRounded/><b>فایل PDF</b><small>به‌زودی</small></button><button className="source-option disabled" disabled><AudiotrackRounded/><b>ضبط صدا</b><small>به‌زودی</small></button><button className="source-option disabled" disabled><AudiotrackRounded/><b>آپلود صوت</b><small>به‌زودی</small></button></div><Button onClick={()=>setStep("pet")}>تغییر پرونده</Button></div>}
  {step==="analyzing"&&<div className="ai-reading"><div className="ai-preview">{preview&&<img src={preview} alt="مدرک پزشکی"/>}</div><CircularProgress/><b>در حال استخراج اطلاعات…</b><small>نسخه، تشخیص، داروها و تاریخ شناسایی می‌شوند.</small></div>}
  {step==="review"&&<Box component="form" onSubmit={save}><DialogContent className="review-grid quick-review"><aside className="document-preview">{preview?<img src={preview} alt="تصویر مدرک پزشکی"/>:<DescriptionRounded/>}<b>تصویر اصلی</b><span>همراه رکورد ذخیره می‌شود</span></aside><Stack spacing={2} className="extracted-form"><Alert severity="success" icon={<CheckCircleRounded/>}>اطلاعات از تصویر استخراج شد؛ قبل از ثبت نهایی بازبینی کنید.</Alert><FormControl size="small"><InputLabel>نوع مدرک</InputLabel><Select label="نوع مدرک" value={values.recordType} onChange={set("recordType")}>{recordTypes.map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</Select></FormControl><TextField label="عنوان" required value={values.title} onChange={set("title")}/><TextField label="تاریخ" value={values.date} onChange={set("date")}/><div className="form-row"><TextField label="کلینیک" value={values.clinic} onChange={set("clinic")}/><TextField label="دامپزشک" value={values.veterinarian} onChange={set("veterinarian")}/></div><TextField multiline rows={2} label="تشخیص" value={values.diagnosis} onChange={set("diagnosis")}/><TextField multiline rows={2} label="داروها و دستور مصرف" value={values.medications} onChange={set("medications")}/><TextField multiline rows={2} label="یادداشت" value={values.notes} onChange={set("notes")}/></Stack></DialogContent><DialogActions><Button onClick={()=>setStep("source")}>تغییر تصویر</Button><Button variant="contained" type="submit" disabled={busy}>{busy?<CircularProgress size={20}/>:`ثبت در پرونده ${selectedPet?.name}`}</Button></DialogActions></Box>}
  </Dialog>;
}
