-- Vetrica taxonomy library: database-driven species and breeds
-- Source: /Users/toman/Downloads/vetrica_taxonomy_codex_prompt.txt

create extension if not exists pgcrypto;

do $$ begin create type public.species_code as enum ('DOG','CAT','RABBIT','BIRD','OTHER'); exception when duplicate_object then null; end $$;
do $$ begin create type public.custom_taxonomy_type as enum ('SPECIES','BREED'); exception when duplicate_object then null; end $$;
do $$ begin create type public.taxonomy_review_status as enum ('PENDING','APPROVED','REJECTED','MERGED'); exception when duplicate_object then null; end $$;

create table if not exists public.species (
  id uuid primary key default gen_random_uuid(),
  code public.species_code not null unique,
  name_fa text not null,
  name_en text not null,
  is_active boolean not null default true,
  is_custom_allowed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.breeds (
  id uuid primary key default gen_random_uuid(),
  species_id uuid not null references public.species(id) on delete cascade,
  code text not null unique,
  name_fa text not null,
  name_en text not null,
  group_fa text,
  group_en text,
  is_active boolean not null default true,
  is_verified boolean not null default true,
  source text not null default 'vetrica_seed',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.custom_pet_taxonomy_entries (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  pet_id uuid references public.pets(id) on delete cascade,
  type public.custom_taxonomy_type not null,
  species_id uuid references public.species(id),
  raw_value text not null,
  normalized_value text,
  review_status public.taxonomy_review_status not null default 'PENDING',
  merged_into_species_id uuid references public.species(id),
  merged_into_breed_id uuid references public.breeds(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.pets add column if not exists species_id uuid references public.species(id);
alter table public.pets add column if not exists breed_id uuid references public.breeds(id);
alter table public.pets add column if not exists custom_species_text text;
alter table public.pets add column if not exists custom_breed_text text;

create index if not exists species_active_code_idx on public.species(is_active, code);
create index if not exists breeds_species_active_idx on public.breeds(species_id, is_active);
create index if not exists breeds_search_idx on public.breeds using gin (to_tsvector('simple', coalesce(name_fa,'') || ' ' || coalesce(name_en,'') || ' ' || coalesce(group_fa,'') || ' ' || coalesce(group_en,'')));
create index if not exists custom_taxonomy_review_idx on public.custom_pet_taxonomy_entries(review_status, created_at desc);
create index if not exists custom_taxonomy_user_idx on public.custom_pet_taxonomy_entries(user_id, created_at desc);

alter table public.species enable row level security;
alter table public.breeds enable row level security;
alter table public.custom_pet_taxonomy_entries enable row level security;

drop policy if exists "active species readable" on public.species;
create policy "active species readable" on public.species for select to authenticated using (is_active);
drop policy if exists "active breeds readable" on public.breeds;
create policy "active breeds readable" on public.breeds for select to authenticated using (is_active);
drop policy if exists "users view own custom taxonomy" on public.custom_pet_taxonomy_entries;
create policy "users view own custom taxonomy" on public.custom_pet_taxonomy_entries for select to authenticated using (user_id = (select auth.uid()));
drop policy if exists "users create own custom taxonomy" on public.custom_pet_taxonomy_entries;
create policy "users create own custom taxonomy" on public.custom_pet_taxonomy_entries for insert to authenticated with check (user_id = (select auth.uid()));

insert into public.species (code, name_fa, name_en, is_active, is_custom_allowed) values
  ('DOG'::public.species_code, 'سگ', 'Dog', true, false),
  ('CAT'::public.species_code, 'گربه', 'Cat', true, false),
  ('RABBIT'::public.species_code, 'خرگوش', 'Rabbit', true, false),
  ('BIRD'::public.species_code, 'پرنده', 'Bird', true, false),
  ('OTHER'::public.species_code, 'سایر', 'Other', true, true)
on conflict (code) do update set name_fa=excluded.name_fa, name_en=excluded.name_en, is_active=excluded.is_active, is_custom_allowed=excluded.is_custom_allowed, updated_at=now();

with breed_seed (species_code, code, group_en, group_fa, name_fa, name_en, source) as (
  values
    ('DOG'::public.species_code, 'DOG_GERMAN_SHEPHERD', 'Herding', 'گله‌بان و چوپان', 'ژرمن شپرد', 'German Shepherd', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BELGIAN_MALINOIS', 'Herding', 'گله‌بان و چوپان', 'بلژین مالینویز', 'Belgian Malinois', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BELGIAN_GROENENDAEL', 'Herding', 'گله‌بان و چوپان', 'بلژین گروئنندال', 'Belgian Groenendael', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BELGIAN_LAEKENOIS', 'Herding', 'گله‌بان و چوپان', 'بلژین لاکنوا', 'Belgian Laekenois', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BELGIAN_TERVUREN', 'Herding', 'گله‌بان و چوپان', 'بلژین تروورن', 'Belgian Tervuren', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BORDER_COLLIE', 'Herding', 'گله‌بان و چوپان', 'بردر کولی', 'Border Collie', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_ROUGH_COLLIE', 'Herding', 'گله‌بان و چوپان', 'راف کولی', 'Rough Collie', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_SMOOTH_COLLIE', 'Herding', 'گله‌بان و چوپان', 'اسموث کولی', 'Smooth Collie', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_AUSTRALIAN_SHEPHERD', 'Herding', 'گله‌بان و چوپان', 'استرالیان شپرد', 'Australian Shepherd', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_MINIATURE_AMERICAN_SHEPHERD', 'Herding', 'گله‌بان و چوپان', 'مینیاتوری آمریکایی شپرد', 'Miniature American Shepherd', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_AUSTRALIAN_CATTLE_DOG', 'Herding', 'گله‌بان و چوپان', 'استرالیان کتل داگ', 'Australian Cattle Dog', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BLUE_HEELER', 'Herding', 'گله‌بان و چوپان', 'بلو هیلر', 'Blue Heeler', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_RED_HEELER', 'Herding', 'گله‌بان و چوپان', 'رد هیلر', 'Red Heeler', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_OLD_ENGLISH_SHEEPDOG', 'Herding', 'گله‌بان و چوپان', 'اولد انگلیش شیپ‌داگ', 'Old English Sheepdog', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BEARDED_COLLIE', 'Herding', 'گله‌بان و چوپان', 'بیردد کولی', 'Bearded Collie', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_POLISH_LOWLAND_SHEEPDOG', 'Herding', 'گله‌بان و چوپان', 'پولیش لولند شیپ‌داگ', 'Polish Lowland Sheepdog', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BRIARD', 'Herding', 'گله‌بان و چوپان', 'بریار', 'Briard', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BOUVIER_DES_FLANDRES', 'Herding', 'گله‌بان و چوپان', 'بوویه د فلاندر', 'Bouvier des Flandres', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BERGAMASCO_SHEPHERD', 'Herding', 'گله‌بان و چوپان', 'برگاماسکو شپرد', 'Bergamasco Shepherd', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_CATALAN_SHEEPDOG', 'Herding', 'گله‌بان و چوپان', 'کاتالان شیپ‌داگ', 'Catalan Sheepdog', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_SHETLAND_SHEEPDOG', 'Herding', 'گله‌بان و چوپان', 'شتلند شیپ‌داگ', 'Shetland Sheepdog', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_PEMBROKE_WELSH_CORGI', 'Herding', 'گله‌بان و چوپان', 'ولش کورگی پمبروک', 'Pembroke Welsh Corgi', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_CARDIGAN_WELSH_CORGI', 'Herding', 'گله‌بان و چوپان', 'ولش کورگی کاردیگان', 'Cardigan Welsh Corgi', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BEAUCERON', 'Herding', 'گله‌بان و چوپان', 'بوسرون', 'Beauceron', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_CANAAN_DOG', 'Herding', 'گله‌بان و چوپان', 'کنعان داگ', 'Canaan Dog', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_KOMONDOR', 'Herding', 'گله‌بان و چوپان', 'کوموندور', 'Komondor', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_PULI', 'Herding', 'گله‌بان و چوپان', 'پولی', 'Puli', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_MUDI', 'Herding', 'گله‌بان و چوپان', 'مودی', 'Mudi', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_PUMI', 'Herding', 'گله‌بان و چوپان', 'پومی', 'Pumi', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_ROTTWEILER', 'Working', 'کاری و نگهبان', 'روتوایلر', 'Rottweiler', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_DOBERMAN_PINSCHER', 'Working', 'کاری و نگهبان', 'دوبرمن پینشر', 'Doberman Pinscher', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BOXER', 'Working', 'کاری و نگهبان', 'باکسر', 'Boxer', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_GREAT_DANE', 'Working', 'کاری و نگهبان', 'گریت دین', 'Great Dane', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_SAINT_BERNARD', 'Working', 'کاری و نگهبان', 'سنت برنارد', 'Saint Bernard', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_NEWFOUNDLAND', 'Working', 'کاری و نگهبان', 'نیوفاندلند', 'Newfoundland', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BERNESE_MOUNTAIN_DOG', 'Working', 'کاری و نگهبان', 'برنیز مانتین داگ', 'Bernese Mountain Dog', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_LEONBERGER', 'Working', 'کاری و نگهبان', 'لئونبرگر', 'Leonberger', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BULLMASTIFF', 'Working', 'کاری و نگهبان', 'بولماستیف', 'Bullmastiff', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_ENGLISH_MASTIFF', 'Working', 'کاری و نگهبان', 'انگلیش ماستیف', 'English Mastiff', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_NEAPOLITAN_MASTIFF', 'Working', 'کاری و نگهبان', 'ناپولیتن ماستیف', 'Neapolitan Mastiff', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_CANE_CORSO', 'Working', 'کاری و نگهبان', 'کین کورسو', 'Cane Corso', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_DOGO_ARGENTINO', 'Working', 'کاری و نگهبان', 'دوگو آرژانتینو', 'Dogo Argentino', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_AKITA', 'Working', 'کاری و نگهبان', 'آکیتا', 'Akita', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_AMERICAN_AKITA', 'Working', 'کاری و نگهبان', 'آکیتای آمریکایی', 'American Akita', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_SAMOYED', 'Working', 'کاری و نگهبان', 'ساموید', 'Samoyed', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_SIBERIAN_HUSKY', 'Working', 'کاری و نگهبان', 'سیبریان هاسکی', 'Siberian Husky', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_ALASKAN_MALAMUTE', 'Working', 'کاری و نگهبان', 'آلاسکن مالاموت', 'Alaskan Malamute', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_TIBETAN_MASTIFF', 'Working', 'کاری و نگهبان', 'تایبتن ماستیف', 'Tibetan Mastiff', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_ANATOLIAN_SHEPHERD_DOG', 'Working', 'کاری و نگهبان', 'آناتولیان شپرد', 'Anatolian Shepherd Dog', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_KANGAL_SHEPHERD_DOG', 'Working', 'کاری و نگهبان', 'کانگال', 'Kangal Shepherd Dog', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_KUVASZ', 'Working', 'کاری و نگهبان', 'کوواز', 'Kuvasz', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_GREAT_PYRENEES', 'Working', 'کاری و نگهبان', 'گریت پیرنیز', 'Great Pyrenees', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_ESTRELA_MOUNTAIN_DOG', 'Working', 'کاری و نگهبان', 'استرلا مانتین داگ', 'Estrela Mountain Dog', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BLACK_RUSSIAN_TERRIER', 'Working', 'کاری و نگهبان', 'بلک روسین تریر', 'Black Russian Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BOERBOEL', 'Working', 'کاری و نگهبان', 'بوربول', 'Boerboel', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_SHAR_PEI', 'Working', 'کاری و نگهبان', 'شارپی', 'Shar Pei', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_DOGUE_DE_BORDEAUX', 'Working', 'کاری و نگهبان', 'دوگ دو بوردو', 'Dogue de Bordeaux', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_LANDSEER', 'Working', 'کاری و نگهبان', 'لندسیر', 'Landseer', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_HOVAWART', 'Working', 'کاری و نگهبان', 'هواوارت', 'Hovawart', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_AIREDALE_TERRIER', 'Terrier', 'تریر', 'ایردیل تریر', 'Airedale Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_AMERICAN_STAFFORDSHIRE_TERRIER', 'Terrier', 'تریر', 'آمریکن استافوردشایر تریر', 'American Staffordshire Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_STAFFORDSHIRE_BULL_TERRIER', 'Terrier', 'تریر', 'استافوردشایر بول تریر', 'Staffordshire Bull Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BULL_TERRIER', 'Terrier', 'تریر', 'بول تریر', 'Bull Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_MINIATURE_BULL_TERRIER', 'Terrier', 'تریر', 'مینیاتور بول تریر', 'Miniature Bull Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_JACK_RUSSELL_TERRIER', 'Terrier', 'تریر', 'جک راسل تریر', 'Jack Russell Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_PARSON_RUSSELL_TERRIER', 'Terrier', 'تریر', 'پارسون راسل تریر', 'Parson Russell Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_RUSSELL_TERRIER', 'Terrier', 'تریر', 'راسل تریر', 'Russell Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_SMOOTH_FOX_TERRIER', 'Terrier', 'تریر', 'فاکس تریر موصاف', 'Smooth Fox Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_WIRE_FOX_TERRIER', 'Terrier', 'تریر', 'فاکس تریر موبلند', 'Wire Fox Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_YORKSHIRE_TERRIER', 'Terrier', 'تریر', 'یورکشایر تریر', 'Yorkshire Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_WEST_HIGHLAND_WHITE_TERRIER', 'Terrier', 'تریر', 'وست هایلند وایت تریر', 'West Highland White Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_SCOTTISH_TERRIER', 'Terrier', 'تریر', 'اسکاتیش تریر', 'Scottish Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_CAIRN_TERRIER', 'Terrier', 'تریر', 'کرن تریر', 'Cairn Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_NORWICH_TERRIER', 'Terrier', 'تریر', 'نورویچ تریر', 'Norwich Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_NORFOLK_TERRIER', 'Terrier', 'تریر', 'نورفولک تریر', 'Norfolk Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BORDER_TERRIER', 'Terrier', 'تریر', 'بردر تریر', 'Border Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_DANDIE_DINMONT_TERRIER', 'Terrier', 'تریر', 'دندی دینمونت تریر', 'Dandie Dinmont Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_SEALYHAM_TERRIER', 'Terrier', 'تریر', 'سیلیهام تریر', 'Sealyham Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_SKYE_TERRIER', 'Terrier', 'تریر', 'اسکای تریر', 'Skye Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BEDLINGTON_TERRIER', 'Terrier', 'تریر', 'بدلینگتون تریر', 'Bedlington Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_LAKELAND_TERRIER', 'Terrier', 'تریر', 'لیکلند تریر', 'Lakeland Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_WELSH_TERRIER', 'Terrier', 'تریر', 'ولش تریر', 'Welsh Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_IRISH_TERRIER', 'Terrier', 'تریر', 'آیریش تریر', 'Irish Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_GLEN_OF_IMAAL_TERRIER', 'Terrier', 'تریر', 'گلن آو ایمال تریر', 'Glen of Imaal Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_KERRY_BLUE_TERRIER', 'Terrier', 'تریر', 'کری بلو تریر', 'Kerry Blue Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_SOFT_COATED_WHEATEN_TERRIER', 'Terrier', 'تریر', 'سافت کوتد ویتن تریر', 'Soft Coated Wheaten Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_CESKY_TERRIER', 'Terrier', 'تریر', 'سزکی تریر', 'Cesky Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_JAPANESE_TERRIER', 'Terrier', 'تریر', 'جاپانیز تریر', 'Japanese Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BRAZILIAN_TERRIER', 'Terrier', 'تریر', 'برازیلین تریر', 'Brazilian Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_RAT_TERRIER', 'Terrier', 'تریر', 'رت تریر', 'Rat Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_MANCHESTER_TERRIER', 'Terrier', 'تریر', 'منچستر تریر', 'Manchester Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_AUSTRALIAN_TERRIER', 'Terrier', 'تریر', 'استرالیان تریر', 'Australian Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_AUSTRALIAN_SILKY_TERRIER', 'Terrier', 'تریر', 'استرالیان سیلکی تریر', 'Australian Silky Terrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_POMERANIAN', 'Spitz & Northern', 'اسپیتز و نژادهای شمالی', 'پامرانیان', 'Pomeranian', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_SHIBA_INU', 'Spitz & Northern', 'اسپیتز و نژادهای شمالی', 'شیبا اینو', 'Shiba Inu', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_KISHU_KEN', 'Spitz & Northern', 'اسپیتز و نژادهای شمالی', 'کیشو کن', 'Kishu Ken', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_HOKKAIDO', 'Spitz & Northern', 'اسپیتز و نژادهای شمالی', 'هوکایدو', 'Hokkaido', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_KAI_KEN', 'Spitz & Northern', 'اسپیتز و نژادهای شمالی', 'کای کن', 'Kai Ken', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_SHIKOKU', 'Spitz & Northern', 'اسپیتز و نژادهای شمالی', 'شیکوکو', 'Shikoku', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_JAPANESE_SPITZ', 'Spitz & Northern', 'اسپیتز و نژادهای شمالی', 'ژاپنی اسپیتز', 'Japanese Spitz', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_FINNISH_SPITZ', 'Spitz & Northern', 'اسپیتز و نژادهای شمالی', 'فنلاندی اسپیتز', 'Finnish Spitz', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_FINNISH_LAPPHUND', 'Spitz & Northern', 'اسپیتز و نژادهای شمالی', 'فنلاندی لاپفوند', 'Finnish Lapphund', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_SWEDISH_LAPPHUND', 'Spitz & Northern', 'اسپیتز و نژادهای شمالی', 'سوئدی لاپفوند', 'Swedish Lapphund', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_NORWEGIAN_ELKHOUND_GREY', 'Spitz & Northern', 'اسپیتز و نژادهای شمالی', 'نروژی الخوند خاکستری', 'Norwegian Elkhound Grey', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_NORWEGIAN_ELKHOUND_BLACK', 'Spitz & Northern', 'اسپیتز و نژادهای شمالی', 'نروژی الخوند سیاه', 'Norwegian Elkhound Black', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_NORWEGIAN_LUNDEHUND', 'Spitz & Northern', 'اسپیتز و نژادهای شمالی', 'نروژی لوندهاوند', 'Norwegian Lundehund', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_KEESHOND', 'Spitz & Northern', 'اسپیتز و نژادهای شمالی', 'کیشوند', 'Keeshond', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_CHOW_CHOW', 'Spitz & Northern', 'اسپیتز و نژادهای شمالی', 'چوچو', 'Chow Chow', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_EURASIER', 'Spitz & Northern', 'اسپیتز و نژادهای شمالی', 'اوراسیر', 'Eurasier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_CANADIAN_ESKIMO_DOG', 'Spitz & Northern', 'اسپیتز و نژادهای شمالی', 'کانادین اسکیمو داگ', 'Canadian Eskimo Dog', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_GREENLAND_DOG', 'Spitz & Northern', 'اسپیتز و نژادهای شمالی', 'گرینلند داگ', 'Greenland Dog', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_YAKUTIAN_LAIKA', 'Spitz & Northern', 'اسپیتز و نژادهای شمالی', 'یاکوتین لایکا', 'Yakutian Laika', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BASENJI', 'Spitz & Northern', 'اسپیتز و نژادهای شمالی', 'باسنجی', 'Basenji', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BEAGLE', 'Scent Hound', 'شکاری بویایی', 'بیگل', 'Beagle', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_HARRIER', 'Scent Hound', 'شکاری بویایی', 'هریر', 'Harrier', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BASSET_HOUND', 'Scent Hound', 'شکاری بویایی', 'بست هاند', 'Basset Hound', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BLOODHOUND', 'Scent Hound', 'شکاری بویایی', 'بلادهاند', 'Bloodhound', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BLACK_AND_TAN_COONHOUND', 'Scent Hound', 'شکاری بویایی', 'بلک اند تن کون‌هاوند', 'Black and Tan Coonhound', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BLUETICK_COONHOUND', 'Scent Hound', 'شکاری بویایی', 'بلوتیک کون‌هاوند', 'Bluetick Coonhound', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_REDBONE_COONHOUND', 'Scent Hound', 'شکاری بویایی', 'ردبون کون‌هاوند', 'Redbone Coonhound', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_TREEING_WALKER_COONHOUND', 'Scent Hound', 'شکاری بویایی', 'تریینگ واکر کون‌هاوند', 'Treeing Walker Coonhound', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_PLOTT_HOUND', 'Scent Hound', 'شکاری بویایی', 'پلات هاند', 'Plott Hound', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_OTTERHOUND', 'Scent Hound', 'شکاری بویایی', 'اوترهاوند', 'Otterhound', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_GREYHOUND', 'Sighthound', 'شکاری بینایی', 'گری‌هاوند', 'Greyhound', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_WHIPPET', 'Sighthound', 'شکاری بینایی', 'ویپت', 'Whippet', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_ITALIAN_GREYHOUND', 'Sighthound', 'شکاری بینایی', 'ایتالیان گری‌هاوند', 'Italian Greyhound', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_SALUKI', 'Sighthound', 'شکاری بینایی', 'سالوکی', 'Saluki', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_AFGHAN_HOUND', 'Sighthound', 'شکاری بینایی', 'افغان هاوند', 'Afghan Hound', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BORZOI', 'Sighthound', 'شکاری بینایی', 'بورزوی', 'Borzoi', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_AZAWAKH', 'Sighthound', 'شکاری بینایی', 'آزاواک', 'Azawakh', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_SLOUGHI', 'Sighthound', 'شکاری بینایی', 'اسلوگی', 'Sloughi', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_IRISH_WOLFHOUND', 'Sighthound', 'شکاری بینایی', 'آیریش ولف‌هاوند', 'Irish Wolfhound', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_SCOTTISH_DEERHOUND', 'Sighthound', 'شکاری بینایی', 'اسکاتیش دیرهاوند', 'Scottish Deerhound', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_GOLDEN_RETRIEVER', 'Retriever', 'رتریور', 'گلدن رتریور', 'Golden Retriever', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_LABRADOR_RETRIEVER', 'Retriever', 'رتریور', 'لابرادور رتریور', 'Labrador Retriever', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_FLAT_COATED_RETRIEVER', 'Retriever', 'رتریور', 'فلت کوتد رتریور', 'Flat-Coated Retriever', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_CURLY_COATED_RETRIEVER', 'Retriever', 'رتریور', 'کرلی کوتد رتریور', 'Curly-Coated Retriever', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_CHESAPEAKE_BAY_RETRIEVER', 'Retriever', 'رتریور', 'چساپیک بی رتریور', 'Chesapeake Bay Retriever', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_NOVA_SCOTIA_DUCK_TOLLING_RETRIEVER', 'Retriever', 'رتریور', 'نووا اسکوشیا داک تولینگ رتریور', 'Nova Scotia Duck Tolling Retriever', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_ENGLISH_COCKER_SPANIEL', 'Spaniel', 'اسپانیل', 'کاکر اسپانیل انگلیسی', 'English Cocker Spaniel', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_AMERICAN_COCKER_SPANIEL', 'Spaniel', 'اسپانیل', 'کاکر اسپانیل آمریکایی', 'American Cocker Spaniel', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_ENGLISH_SPRINGER_SPANIEL', 'Spaniel', 'اسپانیل', 'اسپرینگر اسپانیل انگلیسی', 'English Springer Spaniel', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_WELSH_SPRINGER_SPANIEL', 'Spaniel', 'اسپانیل', 'ولش اسپرینگر اسپانیل', 'Welsh Springer Spaniel', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_MALTESE', 'Toy & Companion', 'عروسکی و همراه', 'مالتیز', 'Maltese', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_SHIH_TZU', 'Toy & Companion', 'عروسکی و همراه', 'شیتزو', 'Shih Tzu', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_PUG', 'Toy & Companion', 'عروسکی و همراه', 'پاگ', 'Pug', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_CHIHUAHUA', 'Toy & Companion', 'عروسکی و همراه', 'چیواوا', 'Chihuahua', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_POODLE', 'Toy & Companion', 'عروسکی و همراه', 'پودل', 'Poodle', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_BICHON_FRISE', 'Toy & Companion', 'عروسکی و همراه', 'بیچون فریز', 'Bichon Frise', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_DACHSHUND', 'Toy & Companion', 'عروسکی و همراه', 'داشهوند', 'Dachshund', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_PERSIAN', 'Longhair', 'مو بلند', 'پرشین', 'Persian', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_EXOTIC_SHORTHAIR', 'Longhair', 'مو بلند', 'اگزوتیک شورت‌هیر', 'Exotic Shorthair', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_MAINE_COON', 'Longhair', 'مو بلند', 'مین کون', 'Maine Coon', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_RAGDOLL', 'Longhair', 'مو بلند', 'راگدال', 'Ragdoll', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_BIRMAN', 'Longhair', 'مو بلند', 'بیرمن', 'Birman', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_NORWEGIAN_FOREST_CAT', 'Longhair', 'مو بلند', 'نروژین فارست کت', 'Norwegian Forest Cat', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_SIBERIAN', 'Longhair', 'مو بلند', 'سیبری', 'Siberian', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_TURKISH_ANGORA', 'Longhair', 'مو بلند', 'ترکیش آنگورا', 'Turkish Angora', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_TURKISH_VAN', 'Longhair', 'مو بلند', 'ترکیش وان', 'Turkish Van', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_HIMALAYAN', 'Longhair', 'مو بلند', 'هیمالین', 'Himalayan', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_BRITISH_SHORTHAIR', 'Shorthair', 'مو کوتاه', 'بریتیش شورت‌هیر', 'British Shorthair', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_AMERICAN_SHORTHAIR', 'Shorthair', 'مو کوتاه', 'آمریکن شورت‌هیر', 'American Shorthair', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_EUROPEAN_SHORTHAIR', 'Shorthair', 'مو کوتاه', 'اروپین شورت‌هیر', 'European Shorthair', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_SCOTTISH_FOLD', 'Shorthair', 'مو کوتاه', 'اسکاتیش فولد', 'Scottish Fold', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_SCOTTISH_STRAIGHT', 'Shorthair', 'مو کوتاه', 'اسکاتیش استریت', 'Scottish Straight', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_BENGAL', 'Shorthair', 'مو کوتاه', 'بنگال', 'Bengal', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_SAVANNAH', 'Shorthair', 'مو کوتاه', 'ساوانا', 'Savannah', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_ABYSSINIAN', 'Shorthair', 'مو کوتاه', 'ابیسینیان', 'Abyssinian', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_SOMALI', 'Shorthair', 'مو کوتاه', 'سومالی', 'Somali', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_RUSSIAN_BLUE', 'Shorthair', 'مو کوتاه', 'روسین بلو', 'Russian Blue', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_CHARTREUX', 'Shorthair', 'مو کوتاه', 'شارتره', 'Chartreux', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_KORAT', 'Shorthair', 'مو کوتاه', 'کورات', 'Korat', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_BURMESE', 'Shorthair', 'مو کوتاه', 'برمی', 'Burmese', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_BOMBAY', 'Shorthair', 'مو کوتاه', 'بمبئی', 'Bombay', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_TONKINESE', 'Shorthair', 'مو کوتاه', 'تونکینیز', 'Tonkinese', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_SIAMESE', 'Shorthair', 'مو کوتاه', 'سیامی', 'Siamese', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_ORIENTAL_SHORTHAIR', 'Shorthair', 'مو کوتاه', 'اورینتال شورت‌هیر', 'Oriental Shorthair', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_EGYPTIAN_MAU', 'Shorthair', 'مو کوتاه', 'مصری مائو', 'Egyptian Mau', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_SELKIRK_REX', 'Rex & Hairless', 'رکس و بی‌مو', 'سلکرک رکس', 'Selkirk Rex', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_CORNISH_REX', 'Rex & Hairless', 'رکس و بی‌مو', 'کورنیش رکس', 'Cornish Rex', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_DEVON_REX', 'Rex & Hairless', 'رکس و بی‌مو', 'دوون رکس', 'Devon Rex', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_SPHYNX', 'Rex & Hairless', 'رکس و بی‌مو', 'اسفینکس', 'Sphynx', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_MANX', 'Bobtail & Special Body', 'دم‌کوتاه و فرم بدنی خاص', 'منکس', 'Manx', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_MUNCHKIN', 'Bobtail & Special Body', 'دم‌کوتاه و فرم بدنی خاص', 'مانچکین', 'Munchkin', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_TOYGER', 'Hybrid & Rare', 'هیبرید و کمیاب', 'تویگر', 'Toyger', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_ARABIAN_MAU', 'Regional', 'منطقه‌ای و بومی', 'عربین مائو', 'Arabian Mau', 'vetrica_seed'),
    ('CAT'::public.species_code, 'CAT_CYPRUS_CAT', 'Regional', 'منطقه‌ای و بومی', 'قبرسی', 'Cyprus Cat', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_MACAW', 'Parrot', 'طوطی‌سانان', 'ماکائو', 'Macaw', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_AFRICAN_GREY_PARROT', 'Parrot', 'طوطی‌سانان', 'کاسکو', 'African Grey Parrot', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_COCKATOO', 'Parrot', 'طوطی‌سانان', 'کاکادو', 'Cockatoo', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_COCKATIEL', 'Parrot', 'طوطی‌سانان', 'عروس هلندی', 'Cockatiel', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_BUDGERIGAR', 'Parrot', 'طوطی‌سانان', 'مرغ عشق', 'Budgerigar', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_LOVEBIRD', 'Parrot', 'طوطی‌سانان', 'لاوبرد', 'Lovebird', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_CONURE', 'Parrot', 'طوطی‌سانان', 'کانور', 'Conure', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_ECLECTUS_PARROT', 'Parrot', 'طوطی‌سانان', 'اکلکتوس', 'Eclectus Parrot', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_AMAZON_PARROT', 'Parrot', 'طوطی‌سانان', 'آمازون', 'Amazon Parrot', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_LORIKEET', 'Parrot', 'طوطی‌سانان', 'لوری', 'Lorikeet', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_QUAKER_PARROT', 'Parrot', 'طوطی‌سانان', 'کوئیکر', 'Quaker Parrot', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_SENEGAL_PARROT', 'Parrot', 'طوطی‌سانان', 'طوطی سنگالی', 'Senegal Parrot', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_ALEXANDRINE_PARAKEET', 'Parrot', 'طوطی‌سانان', 'پاراکیت الکساندرین', 'Alexandrine Parakeet', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_INDIAN_RINGNECK_PARAKEET', 'Parrot', 'طوطی‌سانان', 'رینگ‌نک هندی', 'Indian Ringneck Parakeet', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_CANARY', 'Finch & Songbird', 'سهره‌سانان و آوازخوان', 'قناری', 'Canary', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_ZEBRA_FINCH', 'Finch & Songbird', 'سهره‌سانان و آوازخوان', 'فنچ زبرا', 'Zebra Finch', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_GOULDIAN_FINCH', 'Finch & Songbird', 'سهره‌سانان و آوازخوان', 'فنچ گولدین', 'Gouldian Finch', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_MYNA', 'Finch & Songbird', 'سهره‌سانان و آوازخوان', 'مینا', 'Myna', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_PIGEON', 'Pigeon & Dove', 'کبوترسانان', 'کبوتر', 'Pigeon', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_HOMING_PIGEON', 'Pigeon & Dove', 'کبوترسانان', 'کبوتر نامه‌بر', 'Homing Pigeon', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_DOVE', 'Pigeon & Dove', 'کبوترسانان', 'قمری', 'Dove', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_CHICKEN', 'Poultry', 'ماکیان', 'مرغ', 'Chicken', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_ROOSTER', 'Poultry', 'ماکیان', 'خروس', 'Rooster', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_TURKEY', 'Poultry', 'ماکیان', 'بوقلمون', 'Turkey', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_QUAIL', 'Poultry', 'ماکیان', 'بلدرچین', 'Quail', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_PARTRIDGE', 'Poultry', 'ماکیان', 'کبک', 'Partridge', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_PHEASANT', 'Poultry', 'ماکیان', 'قرقاول', 'Pheasant', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_PEACOCK', 'Poultry', 'ماکیان', 'طاووس', 'Peacock', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_SWAN', 'Waterbird', 'پرندگان آبزی', 'قو', 'Swan', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_GOOSE', 'Waterbird', 'پرندگان آبزی', 'غاز', 'Goose', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_DUCK', 'Waterbird', 'پرندگان آبزی', 'اردک', 'Duck', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_GOLDEN_EAGLE', 'Raptor', 'پرندگان شکاری', 'عقاب طلایی', 'Golden Eagle', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_FALCON', 'Raptor', 'پرندگان شکاری', 'شاهین', 'Falcon', 'vetrica_seed'),
    ('BIRD'::public.species_code, 'BIRD_OWL', 'Raptor', 'پرندگان شکاری', 'جغد', 'Owl', 'vetrica_seed'),
    ('RABBIT'::public.species_code, 'RABBIT_HOLLAND_LOP', 'Companion Rabbit', 'خرگوش خانگی', 'لوپ هلندی', 'Holland Lop', 'vetrica_seed'),
    ('RABBIT'::public.species_code, 'RABBIT_MINI_LOP', 'Companion Rabbit', 'خرگوش خانگی', 'مینی لوپ', 'Mini Lop', 'vetrica_seed'),
    ('RABBIT'::public.species_code, 'RABBIT_NETHERLAND_DWARF', 'Companion Rabbit', 'خرگوش خانگی', 'نترلانند دورف', 'Netherland Dwarf', 'vetrica_seed'),
    ('RABBIT'::public.species_code, 'RABBIT_LIONHEAD', 'Companion Rabbit', 'خرگوش خانگی', 'لاین‌هد', 'Lionhead', 'vetrica_seed'),
    ('RABBIT'::public.species_code, 'RABBIT_REX_RABBIT', 'Companion Rabbit', 'خرگوش خانگی', 'رکس', 'Rex Rabbit', 'vetrica_seed'),
    ('RABBIT'::public.species_code, 'RABBIT_MINI_REX', 'Companion Rabbit', 'خرگوش خانگی', 'مینی رکس', 'Mini Rex', 'vetrica_seed'),
    ('RABBIT'::public.species_code, 'RABBIT_FLEMISH_GIANT', 'Companion Rabbit', 'خرگوش خانگی', 'فلمیش جاینت', 'Flemish Giant', 'vetrica_seed'),
    ('RABBIT'::public.species_code, 'RABBIT_ANGORA_RABBIT', 'Companion Rabbit', 'خرگوش خانگی', 'انگورا', 'Angora Rabbit', 'vetrica_seed'),
    ('RABBIT'::public.species_code, 'RABBIT_DUTCH_RABBIT', 'Companion Rabbit', 'خرگوش خانگی', 'داچ', 'Dutch Rabbit', 'vetrica_seed'),
    ('RABBIT'::public.species_code, 'RABBIT_NEW_ZEALAND_RABBIT', 'Companion Rabbit', 'خرگوش خانگی', 'نیوزیلندی', 'New Zealand Rabbit', 'vetrica_seed'),
    ('DOG'::public.species_code, 'DOG_UNKNOWN', 'System', 'سیستمی', 'نامشخص', 'Unknown', 'system'),
    ('DOG'::public.species_code, 'DOG_OTHER', 'System', 'سیستمی', 'سایر', 'Other', 'system'),
    ('CAT'::public.species_code, 'CAT_UNKNOWN', 'System', 'سیستمی', 'نامشخص', 'Unknown', 'system'),
    ('CAT'::public.species_code, 'CAT_OTHER', 'System', 'سیستمی', 'سایر', 'Other', 'system'),
    ('RABBIT'::public.species_code, 'RABBIT_UNKNOWN', 'System', 'سیستمی', 'نامشخص', 'Unknown', 'system'),
    ('RABBIT'::public.species_code, 'RABBIT_OTHER', 'System', 'سیستمی', 'سایر', 'Other', 'system'),
    ('BIRD'::public.species_code, 'BIRD_UNKNOWN', 'System', 'سیستمی', 'نامشخص', 'Unknown', 'system'),
    ('BIRD'::public.species_code, 'BIRD_OTHER', 'System', 'سیستمی', 'سایر', 'Other', 'system')
)
insert into public.breeds (species_id, code, group_en, group_fa, name_fa, name_en, source, is_active, is_verified)
select s.id, bs.code, bs.group_en, bs.group_fa, bs.name_fa, bs.name_en, bs.source, true, true
from breed_seed bs
join public.species s on s.code = bs.species_code
on conflict (code) do update set species_id=excluded.species_id, group_en=excluded.group_en, group_fa=excluded.group_fa, name_fa=excluded.name_fa, name_en=excluded.name_en, source=excluded.source, is_active=true, is_verified=true, updated_at=now();
